# Generated by Django 5.0.3 on 2024-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_description_event_details_event_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
