# Generated by Django 5.0.3 on 2024-04-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
