# Generated by Django 5.0.3 on 2024-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_event_image_alter_event_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(null=True, upload_to='venues/'),
        ),
    ]
