# Generated by Django 5.0.3 on 2024-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
