# Generated by Django 5.0.3 on 2024-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='scheduleimage',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='speakerimage',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='ticketimage',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='venueimage',
            name='venue',
        ),
        migrations.AddField(
            model_name='speaker',
            name='career',
            field=models.CharField(default='Speaker', max_length=50),
        ),
        migrations.AddField(
            model_name='speaker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(null=True, upload_to='speakers/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AttendantImage',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.DeleteModel(
            name='ScheduleImage',
        ),
        migrations.DeleteModel(
            name='SpeakerImage',
        ),
        migrations.DeleteModel(
            name='TicketImage',
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
