# Generated by Django 5.0.3 on 2024-04-13 19:46

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_speaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=apps.users.models.Account),
        ),
    ]
