# Generated by Django 5.0.3 on 2024-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_views',
            field=models.IntegerField(default=1),
        ),
    ]
